server:
  port: 8082

spring:
  config:
    # import: "optional:file:D:/dev/ai-qa-system/.env[.properties]"
    import: "optional:file:.env[.properties]" # 改为可选，当前目录
  application:
    name: qa-service
  # cloud:
  #   nacos:
  #     discovery:
  #       server-addr: 3.101.113.38:8848
  #       #ip: 127.0.0.1
  #       #port: 8082
  datasource:
    url: jdbc:mysql://database:3306/ai_qa_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ai_qa_system
    # url: jdbc:mysql://database:3306/ai_qa_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    # username: root
    # password: root1234
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimpleMetricsExportAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

deepseek:
  api:
    base-url: https://api.deepseek.com/v1
    key: ${DEEPSEEK_API_KEY:sk-31581bd22e844e1d8387f8570a7f3fdb}
    model: deepseek-chat

logging:
  file:
    name: application.log
    path: logs
  level:
    com.ai.qa.service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  charset:
    console: UTF-8
    file: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: WHEN_AUTHORIZED
    info:
      enabled: true
    metrics:
      enabled: false
  metrics:
    enable:
      process: false
      system: false
